# Generated by Django 5.2 on 2025-04-24 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logging_service', models.CharField(default='', max_length=16)),
                ('settings', models.JSONField(default={'simkl': {'access_token': '', 'account_id': ''}})),
            ],
            options={
                'db_table': 'client',
            },
        ),
    ]
