"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

from environs import Env
from django.contrib.messages import constants as message_constants

from core.tests.helpers import SkipExternalTests
from core.tests.utils import ChromeMode

import os


env = Env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ti!2dlnrgystyzw%ng3km@^7dnhi0-97dx4_uz=5y#6yw_y-67'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "languages.apps.LanguagesConfig",
    "movie_metadata.apps.MovieMetadataConfig",
    "movie_loggers.apps.MovieLoggersConfig",
    "movies.apps.MoviesConfig",
    "db.apps.DbConfig",
    "core.apps.CoreConfig",
    "oauth.apps.OAuthConfig",
    'django.contrib.sessions',
    'django.contrib.staticfiles',
    'django.contrib.messages',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.postgres',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'movie_loggers.middleware.refresh_token.RefreshTokenMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "core" / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.messages.context_processors.messages',
                'django.contrib.auth.context_processors.auth',
                'core.context_processors.is_signed_in_cp',
                'core.context_processors.is_development_cp',
                'core.context_processors.is_test_cp',
                'core.context_processors.is_production_cp',
            ],
            'libraries': {
                "custom_tags": "core.templatetags.custom_tags",
            },
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


DATABASES = {
    'default': {
        "ENGINE": 'django.db.backends.postgresql',
        "NAME": env.str("POSTGRES_DB"),
        "USER": env.str("POSTGRES_USER"),
        "PASSWORD": env.str("POSTGRES_PASSWORD"),
        "HOST": env.str("POSTGRES_HOST"),
        "PORT": env.str("POSTGRES_PORT"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Belgrade'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [BASE_DIR / "core" / "static"]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SESSION_COOKIE_AGE = 60 * 60 * 24 * 365 * 10 # 10 years in seconds

MESSAGE_TAGS = {
    message_constants.SUCCESS: "success bg-green-100 border border-green-400 text-green-700",
    message_constants.ERROR: "error bg-red-100 border border-red-400 text-red-700 ",
}

MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

USER_AGENT = "JustAnotherMovieFinder/1.0.0 (justanothermoviefinder@gmail.com)"

API_REDIRECT_URL = "http://localhost:8000/oauth/"

# Set to NO if you want to temporarily disable
SKIP_EXTERNAL_TESTS = SkipExternalTests.YES

# Set to DEFAULT if you want to temporarily see UI
CHROME_OPTIONS = ChromeMode.HEADLESS.options

DJANGO_ENV = env.str("DJANGO_ENV", "development")
