COUNTRIES = [
    {'abw': 'Aruba'},
    {'afg': 'Afghanistan'},
    {'ago': 'Angola'},
    {'aia': 'Anguilla'},
    {'ala': 'Åland Islands'},
    {'alb': 'Albania'},
    {'and': 'Andorra'},
    {'are': 'United Arab Emirates'},
    {'arg': 'Argentina'},
    {'arm': 'Armenia'},
    {'asm': 'American Samoa'},
    {'ata': 'Antarctica'},
    {'atf': 'French Southern Territories'},
    {'atg': 'Antigua and Barbuda'},
    {'aus': 'Australia'},
    {'aut': 'Austria'},
    {'aze': 'Azerbaijan'},
    {'bdi': 'Burundi'},
    {'bel': 'Belgium'},
    {'ben': 'Benin'},
    {'bes': 'Bonaire, Sint Eustatius and Saba'},
    {'bfa': 'Burkina Faso'},
    {'bgd': 'Bangladesh'},
    {'bgr': 'Bulgaria'},
    {'bhr': 'Bahrain'},
    {'bhs': 'Bahamas'},
    {'bih': 'Bosnia and Herzegovina'},
    {'blm': 'Saint Barthélemy'},
    {'blr': 'Belarus'},
    {'blz': 'Belize'},
    {'bmu': 'Bermuda'},
    {'bol': 'Bolivia'},
    {'bra': 'Brazil'},
    {'brb': 'Barbados'},
    {'brn': 'Brunei Darussalam'},
    {'btn': 'Bhutan'},
    {'bvt': 'Bouvet Island'},
    {'bwa': 'Botswana'},
    {'caf': 'Central African Republic'},
    {'can': 'Canada'},
    {'cck': 'Cocos (Keeling) Islands'},
    {'che': 'Switzerland'},
    {'chl': 'Chile'},
    {'chn': 'China'},
    {'civ': 'Ivory Coast'},
    {'cmr': 'Cameroon'},
    {'cod': 'Congo'},
    {'cog': 'Republic of the Congo'},
    {'cok': 'Cook Islands'},
    {'col': 'Colombia'},
    {'com': 'Comoros'},
    {'cpv': 'Cape Verde'},
    {'cri': 'Costa Rica'},
    {'cub': 'Cuba'},
    {'cuw': 'Curaçao'},
    {'cxr': 'Christmas Island'},
    {'cym': 'Cayman Islands'},
    {'cyp': 'Cyprus'},
    {'cze': 'Czech Republic'},
    {'deu': 'Germany'},
    {'dji': 'Djibouti'},
    {'dma': 'Dominica'},
    {'dnk': 'Denmark'},
    {'dom': 'Dominican Republic'},
    {'dza': 'Algeria'},
    {'ecu': 'Ecuador'},
    {'egy': 'Egypt'},
    {'eri': 'Eritrea'},
    {'esh': 'Western Sahara'},
    {'esp': 'Spain'},
    {'est': 'Estonia'},
    {'eth': 'Ethiopia'},
    {'fin': 'Finland'},
    {'fji': 'Fiji'},
    {'flk': 'The Falkland Islands'},
    {'fra': 'France'},
    {'fro': 'The Faroe Islands'},
    {'fsm': 'Micronesia'},
    {'gab': 'Gabon'},
    {'gbr': 'Great Britain'},
    {'geo': 'Georgia'},
    {'ggy': 'Guernsey'},
    {'gha': 'Ghana'},
    {'gib': 'Gibraltar'},
    {'gin': 'Guinea'},
    {'glp': 'Guadeloupe'},
    {'gmb': 'Gambia'},
    {'gnb': 'Guinea-Bissau'},
    {'gnq': 'Equatorial Guinea'},
    {'grc': 'Greece'},
    {'grd': 'Grenada'},
    {'grl': 'Greenland'},
    {'gtm': 'Guatemala'},
    {'guf': 'French Guiana'},
    {'gum': 'Guam'},
    {'guy': 'Guyana'},
    {'hkg': 'Hong Kong'},
    {'hmd': 'Heard Island and McDonald Islands'},
    {'hnd': 'Honduras'},
    {'hrv': 'Croatia'},
    {'hti': 'Haiti'},
    {'hun': 'Hungary'},
    {'idn': 'Indonesia'},
    {'imn': 'Isle of Man'},
    {'ind': 'India'},
    {'iot': 'British Indian Ocean Territory'},
    {'irl': 'Ireland'},
    {'irn': 'Iran'},
    {'irq': 'Iraq'},
    {'isl': 'Iceland'},
    {'isr': 'Israel'},
    {'ita': 'Italy'},
    {'jam': 'Jamaica'},
    {'jey': 'Jersey'},
    {'jor': 'Jordan'},
    {'jpn': 'Japan'},
    {'kaz': 'Kazakhstan'},
    {'ken': 'Kenya'},
    {'kgz': 'Kyrgyzstan'},
    {'khm': 'Cambodia'},
    {'kir': 'Kiribati'},
    {'kna': 'Saint Christopher and Nevis'},
    {'kor': 'South Korea'},
    {'kwt': 'Kuwait'},
    {'lao': 'Laos'},
    {'lbn': 'Lebanon'},
    {'lbr': 'Liberia'},
    {'lby': 'Libya'},
    {'lca': 'Saint Lucia'},
    {'lie': 'Liechtenstein'},
    {'lka': 'Sri Lanka'},
    {'lso': 'Lesotho'},
    {'ltu': 'Lithuania'},
    {'lux': 'Luxembourg'},
    {'lva': 'Latvia'},
    {'mac': 'Macao'},
    {'maf': 'Saint Martin'},
    {'mar': 'Morocco'},
    {'mco': 'Monaco'},
    {'mda': 'Moldova'},
    {'mdg': 'Madagascar'},
    {'mdv': 'Maldives'},
    {'mex': 'Mexico'},
    {'mhl': 'Marshall Islands'},
    {'mkd': 'Macedonia'},
    {'mli': 'Mali'},
    {'mlt': 'Malta'},
    {'mmr': 'Myanmar'},
    {'mne': 'Montenegro'},
    {'mng': 'Mongolia'},
    {'mnp': 'Northern Mariana Islands'},
    {'moz': 'Mozambique'},
    {'mrt': 'Mauritania'},
    {'msr': 'Montserrat'},
    {'mtq': 'Martinique'},
    {'mus': 'Mauritius'},
    {'mwi': 'Malawi'},
    {'mys': 'Malaysia'},
    {'myt': 'Mayotte'},
    {'nam': 'Namibia'},
    {'ncl': 'New Caledonia'},
    {'ner': 'Niger'},
    {'nfk': 'Norfolk Island'},
    {'nga': 'Nigeria'},
    {'nic': 'Nicaragua'},
    {'niu': 'Niue'},
    {'nld': 'The Netherlands'},
    {'nor': 'Norway'},
    {'npl': 'Nepal'},
    {'nru': 'Nauru'},
    {'nzl': 'New Zealand'},
    {'omn': 'Oman'},
    {'pak': 'Pakistan'},
    {'pan': 'Panama'},
    {'pcn': 'Pitcairn'},
    {'per': 'Peru'},
    {'phl': 'Philippines'},
    {'plw': 'Republic of Palau'},
    {'png': 'Papua New Guinea'},
    {'pol': 'Poland'},
    {'pri': 'Puerto Rico'},
    {'prk': 'North Korea'},
    {'prt': 'Portugal'},
    {'pry': 'Paraguay'},
    {'pse': 'Palestine, State of'},
    {'pyf': 'French Polynesia'},
    {'qat': 'Qatar'},
    {'reu': 'Réunion'},
    {'rou': 'Romania'},
    {'rus': 'Russia'},
    {'rwa': 'Rwanda'},
    {'sau': 'Saudi Arabia'},
    {'sdn': 'Sudan'},
    {'sen': 'Senegal'},
    {'sgp': 'Singapore'},
    {'sgs': 'South Georgia'},
    {'shn': 'Saint Helena, Ascension and Tristan da Cunha'},
    {'sjm': 'Svalbard and Jan Mayen'},
    {'slb': 'Solomon Islands'},
    {'sle': 'Sierra Leone'},
    {'slv': 'El Salvador'},
    {'smr': 'San Marino'},
    {'som': 'Somali Republic'},
    {'spm': 'Saint Pierre and Miquelon'},
    {'srb': 'Serbia'},
    {'ssd': 'South Sudan'},
    {'stp': 'São Tomé and Príncipe'},
    {'sur': 'Suriname'},
    {'svk': 'Slovakia'},
    {'svn': 'Slovenia'},
    {'swe': 'Sweden'},
    {'swz': 'Swaziland'},
    {'sxm': 'Sint Maarten'},
    {'syc': 'Seychelles'},
    {'syr': 'Syrian Arab Republic'},
    {'tca': 'Turks and Caicos Islands'},
    {'tcd': 'Chad'},
    {'tgo': 'Togo'},
    {'tha': 'Thailand'},
    {'tjk': 'Tajikistan'},
    {'tkl': 'Tokelau'},
    {'tkm': 'Turkmenistan'},
    {'tls': 'Timor-Leste'},
    {'ton': 'Tonga'},
    {'tto': 'Trinidad and Tobago'},
    {'tun': 'Tunisia'},
    {'tur': 'Turkey'},
    {'tuv': 'Tuvalu'},
    {'twn': 'Taiwan'},
    {'tza': 'Tanzania'},
    {'uga': 'Uganda'},
    {'ukr': 'Ukraine'},
    {'umi': 'United States Minor Outlying Islands'},
    {'unk': 'Kosovo'},
    {'ury': 'Uruguay'},
    {'usa': 'United States of America'},
    {'uzb': 'Uzbekistan'},
    {'vat': 'Vatican City'},
    {'vct': 'Saint Vincent and the Grenadines'},
    {'ven': 'Venezuela'},
    {'vgb': 'British Virgin Islands'},
    {'vir': 'Virgin Islands of the United States'},
    {'vnm': 'Vietnam'},
    {'vut': 'Vanuatu'},
    {'wlf': 'Wallis and Futuna'},
    {'wsm': 'Samoa'},
    {'yem': 'Yemen'},
    {'yug': 'Yugoslavia'},
    {'zaf': 'South Africa'},
    {'zmb': 'Zambia'},
    {'zwe': 'Zimbabwe'}
]
LANGUAGES = [
    {'aar': {'name': 'Afar', 'nativeName': 'Afaraf'}},
    {'abk': {'name': 'Abkhaz', 'nativeName': 'аҧсуа бызшәа'}},
    {'afr': {'name': 'Afrikaans', 'nativeName': 'Afrikaans'}},
    {'aka': {'name': 'Akan', 'nativeName': 'Akan'}},
    {'amh': {'name': 'Amharic', 'nativeName': 'አማርኛ'}},
    {'ara': {'name': 'Arabic', 'nativeName': 'العربية'}},
    {'arg': {'name': 'Aragonese', 'nativeName': 'aragonés'}},
    {'asm': {'name': 'Assamese', 'nativeName': 'অসমীয়া'}},
    {'ava': {'name': 'Avaric', 'nativeName': 'авар мацӀ'}},
    {'ave': {'name': 'Avestan', 'nativeName': 'avesta'}},
    {'aym': {'name': 'Aymara', 'nativeName': 'aymar aru'}},
    {'aze': {'name': 'Azerbaijani', 'nativeName': 'azərbaycan dili'}},
    {'bak': {'name': 'Bashkir', 'nativeName': 'башҡорт теле'}},
    {'bam': {'name': 'Bambara', 'nativeName': 'bamanankan'}},
    {'bel': {'name': 'Belarusian', 'nativeName': 'беларуская мова'}},
    {'ben': {'name': 'Bengali', 'nativeName': 'বাংলা'}},
    {'bih': {'name': 'Bihari', 'nativeName': 'भोजपुरी'}},
    {'bis': {'name': 'Bislama', 'nativeName': 'Bislama'}},
    {'bod': {'name': 'Tibetan Standard', 'nativeName': 'བོད་ཡིག'}},
    {'bos': {'name': 'Bosnian', 'nativeName': 'bosanski jezik'}},
    {'bre': {'name': 'Breton', 'nativeName': 'brezhoneg'}},
    {'bul': {'name': 'Bulgarian', 'nativeName': 'български език'}},
    {'cat': {'name': 'Catalan', 'nativeName': 'català'}},
    {'ces': {'name': 'Czech', 'nativeName': 'čeština'}},
    {'cha': {'name': 'Chamorro', 'nativeName': 'Chamoru'}},
    {'che': {'name': 'Chechen', 'nativeName': 'нохчийн мотт'}},
    {'chu': {'name': 'Old Church Slavonic', 'nativeName': 'ѩзыкъ словѣньскъ'}},
    {'chv': {'name': 'Chuvash', 'nativeName': 'чӑваш чӗлхи'}},
    {'cor': {'name': 'Cornish', 'nativeName': 'Kernewek'}},
    {'cos': {'name': 'Corsican', 'nativeName': 'corsu'}},
    {'cre': {'name': 'Cree', 'nativeName': 'ᓀᐦᐃᔭᐍᐏᐣ'}},
    {'cym': {'name': 'Welsh', 'nativeName': 'Cymraeg'}},
    {'dan': {'name': 'Danish', 'nativeName': 'dansk'}},
    {'deu': {'name': 'German', 'nativeName': 'Deutsch'}},
    {'div': {'name': 'Divehi', 'nativeName': 'ދިވެހި'}},
    {'dzo': {'name': 'Dzongkha', 'nativeName': 'རྫོང་ཁ'}},
    {'ell': {'name': 'Greek', 'nativeName': 'ελληνική γλώσσα'}},
    {'eng': {'name': 'English', 'nativeName': 'English'}},
    {'epo': {'name': 'Esperanto', 'nativeName': 'Esperanto'}},
    {'est': {'name': 'Estonian', 'nativeName': 'eesti'}},
    {'eus': {'name': 'Basque', 'nativeName': 'euskara'}},
    {'ewe': {'name': 'Ewe', 'nativeName': 'Eʋegbe'}},
    {'fao': {'name': 'Faroese', 'nativeName': 'føroyskt'}},
    {'fas': {'name': 'Persian', 'nativeName': 'فارسی'}},
    {'fij': {'name': 'Fijian', 'nativeName': 'vosa Vakaviti'}},
    {'fin': {'name': 'Finnish', 'nativeName': 'suomi'}},
    {'fra': {'name': 'French', 'nativeName': 'français'}},
    {'fry': {'name': 'Western Frisian', 'nativeName': 'Frysk'}},
    {'ful': {'name': 'Fula', 'nativeName': 'Fulfulde'}},
    {'gla': {'name': 'Scottish Gaelic', 'nativeName': 'Gàidhlig'}},
    {'gle': {'name': 'Irish', 'nativeName': 'Gaeilge'}},
    {'glg': {'name': 'Galician', 'nativeName': 'galego'}},
    {'glv': {'name': 'Manx', 'nativeName': 'Gaelg'}},
    {'grn': {'name': 'Guaraní', 'nativeName': "Avañe'ẽ"}},
    {'guj': {'name': 'Gujarati', 'nativeName': 'ગુજરાતી'}},
    {'hat': {'name': 'Haitian', 'nativeName': 'Kreyòl ayisyen'}},
    {'hau': {'name': 'Hausa', 'nativeName': 'هَوُسَ'}},
    {'heb': {'name': 'Hebrew', 'nativeName': 'עברית'}},
    {'her': {'name': 'Herero', 'nativeName': 'Otjiherero'}},
    {'hin': {'name': 'Hindi', 'nativeName': 'हिन्दी'}},
    {'hmo': {'name': 'Hiri Motu', 'nativeName': 'Hiri Motu'}},
    {'hrv': {'name': 'Croatian', 'nativeName': 'hrvatski jezik'}},
    {'hun': {'name': 'Hungarian', 'nativeName': 'Magyar'}},
    {'hye': {'name': 'Armenian', 'nativeName': 'Հայերեն'}},
    {'ibo': {'name': 'Igbo', 'nativeName': 'Asụsụ Igbo'}},
    {'ido': {'name': 'Ido', 'nativeName': 'Ido'}},
    {'iii': {'name': 'Nuosu', 'nativeName': 'Nuosuhxop'}},
    {'iku': {'name': 'Inuktitut', 'nativeName': 'ᐃᓄᒃᑎᑐᑦ'}},
    {'ile': {'name': 'Interlingue', 'nativeName': 'Interlingue'}},
    {'ina': {'name': 'Interlingua', 'nativeName': 'Interlingua'}},
    {'ind': {'name': 'Indonesian', 'nativeName': 'Bahasa Indonesia'}},
    {'ipk': {'name': 'Inupiaq', 'nativeName': 'Iñupiaq'}},
    {'isl': {'name': 'Icelandic', 'nativeName': 'Íslenska'}},
    {'ita': {'name': 'Italian', 'nativeName': 'italiano'}},
    {'jav': {'name': 'Javanese', 'nativeName': 'basa Jawa'}},
    {'jpn': {'name': 'Japanese', 'nativeName': '日本語'}},
    {'kal': {'name': 'Kalaallisut', 'nativeName': 'kalaallisut'}},
    {'kan': {'name': 'Kannada', 'nativeName': 'ಕನ್ನಡ'}},
    {'kas': {'name': 'Kashmiri', 'nativeName': 'कश्मीरी'}},
    {'kat': {'name': 'Georgian', 'nativeName': 'ქართული'}},
    {'kau': {'name': 'Kanuri', 'nativeName': 'Kanuri'}},
    {'kaz': {'name': 'Kazakh', 'nativeName': 'қазақ тілі'}},
    {'khm': {'name': 'Khmer', 'nativeName': 'ខ្មែរ'}},
    {'kik': {'name': 'Kikuyu', 'nativeName': 'Gĩkũyũ'}},
    {'kin': {'name': 'Kinyarwanda', 'nativeName': 'Ikinyarwanda'}},
    {'kir': {'name': 'Kirghiz', 'nativeName': 'кыргыз тили'}},
    {'kom': {'name': 'Komi', 'nativeName': 'коми кыв'}},
    {'kon': {'name': 'Kongo', 'nativeName': 'KiKongo'}},
    {'kor': {'name': 'Korean', 'nativeName': '한국어'}},
    {'kua': {'name': 'Kwanyama', 'nativeName': 'Kuanyama'}},
    {'kur': {'name': 'Kurdish', 'nativeName': 'Kurdî'}},
    {'lao': {'name': 'Lao', 'nativeName': 'ພາສາລາວ'}},
    {'lat': {'name': 'Latin', 'nativeName': 'latine'}},
    {'lav': {'name': 'Latvian', 'nativeName': 'latviešu valoda'}},
    {'lim': {'name': 'Limburgish', 'nativeName': 'Limburgs'}},
    {'lin': {'name': 'Lingala', 'nativeName': 'Lingála'}},
    {'lit': {'name': 'Lithuanian', 'nativeName': 'lietuvių kalba'}},
    {'ltz': {'name': 'Luxembourgish', 'nativeName': 'Lëtzebuergesch'}},
    {'lub': {'name': 'Luba-Katanga', 'nativeName': 'Luba-Katanga'}},
    {'lug': {'name': 'Luganda', 'nativeName': 'Luganda'}},
    {'mah': {'name': 'Marshallese', 'nativeName': 'Kajin M̧ajeļ'}},
    {'mal': {'name': 'Malayalam', 'nativeName': 'മലയാളം'}},
    {'mar': {'name': 'Marathi', 'nativeName': 'मराठी'}},
    {'mkd': {'name': 'Macedonian', 'nativeName': 'македонски јазик'}},
    {'mlg': {'name': 'Malagasy', 'nativeName': 'Malagasy fiteny'}},
    {'mlt': {'name': 'Maltese', 'nativeName': 'Malti'}},
    {'mon': {'name': 'Mongolian', 'nativeName': 'монгол'}},
    {'mri': {'name': 'Māori', 'nativeName': 'te reo Māori'}},
    {'msa': {'name': 'Malay', 'nativeName': 'bahasa Melayu'}},
    {'mya': {'name': 'Burmese', 'nativeName': 'Burmese'}},
    {'nau': {'name': 'Nauru', 'nativeName': 'Ekakairũ Naoero'}},
    {'nav': {'name': 'Navajo', 'nativeName': 'Diné bizaad'}},
    {'nbl': {'name': 'South Ndebele', 'nativeName': 'isiNdebele'}},
    {'nde': {'name': 'North Ndebele', 'nativeName': 'isiNdebele'}},
    {'ndo': {'name': 'Ndonga', 'nativeName': 'Owambo'}},
    {'nep': {'name': 'Nepali', 'nativeName': 'नेपाली'}},
    {'nld': {'name': 'Dutch', 'nativeName': 'Nederlands'}},
    {'nor': {'name': 'Norwegian', 'nativeName': 'Norsk bokmål'}},
    {'nya': {'name': 'Chewa', 'nativeName': 'chiCheŵa'}},
    {'oci': {'name': 'Occitan', 'nativeName': 'occitan'}},
    {'oji': {'name': 'Ojibwe', 'nativeName': 'ᐊᓂᔑᓈᐯᒧᐎᓐ'}},
    {'ori': {'name': 'Oriya', 'nativeName': 'ଓଡ଼ିଆ'}},
    {'orm': {'name': 'Oromo', 'nativeName': 'Afaan Oromoo'}},
    {'oss': {'name': 'Ossetian', 'nativeName': 'ирон æвзаг'}},
    {'pan': {'name': 'Panjabi', 'nativeName': 'ਪੰਜਾਬੀ'}},
    {'pli': {'name': 'Pāli', 'nativeName': 'पाऴि'}},
    {'pol': {'name': 'Polish', 'nativeName': 'język polski'}},
    {'por': {'name': 'Portuguese - Portugal',
            'nativeName': 'Português - Portugal'}},
    {'pt': {'name': 'Portuguese - Brazil', 'nativeName': 'Português - Brasil'}},
    {'pus': {'name': 'Pashto', 'nativeName': 'پښتو'}},
    {'que': {'name': 'Quechua', 'nativeName': 'Runa Simi'}},
    {'roh': {'name': 'Romansh', 'nativeName': 'rumantsch grischun'}},
    {'ron': {'name': 'Romanian', 'nativeName': 'limba română'}},
    {'run': {'name': 'Kirundi', 'nativeName': 'Ikirundi'}},
    {'rus': {'name': 'Russian', 'nativeName': 'русский язык'}},
    {'sag': {'name': 'Sango', 'nativeName': 'yângâ tî sängö'}},
    {'san': {'name': 'Sanskrit', 'nativeName': 'संस्कृतम्'}},
    {'sin': {'name': 'Sinhala', 'nativeName': 'සිංහල'}},
    {'slk': {'name': 'Slovak', 'nativeName': 'slovenčina'}},
    {'slv': {'name': 'Slovene', 'nativeName': 'slovenski jezik'}},
    {'sme': {'name': 'Northern Sami', 'nativeName': 'Davvisámegiella'}},
    {'smo': {'name': 'Samoan', 'nativeName': "gagana fa'a Samoa"}},
    {'sna': {'name': 'Shona', 'nativeName': 'chiShona'}},
    {'snd': {'name': 'Sindhi', 'nativeName': 'सिन्धी'}},
    {'som': {'name': 'Somali', 'nativeName': 'Soomaaliga'}},
    {'sot': {'name': 'Southern Sotho', 'nativeName': 'Sesotho'}},
    {'spa': {'name': 'Spanish', 'nativeName': 'español'}},
    {'sqi': {'name': 'Albanian', 'nativeName': 'gjuha shqipe'}},
    {'srd': {'name': 'Sardinian', 'nativeName': 'sardu'}},
    {'srp': {'name': 'Serbian', 'nativeName': 'српски језик'}},
    {'ssw': {'name': 'Swati', 'nativeName': 'SiSwati'}},
    {'sun': {'name': 'Sundanese', 'nativeName': 'Basa Sunda'}},
    {'swa': {'name': 'Swahili', 'nativeName': 'Kiswahili'}},
    {'swe': {'name': 'Swedish', 'nativeName': 'svenska'}},
    {'tah': {'name': 'Tahitian', 'nativeName': 'Reo Tahiti'}},
    {'tam': {'name': 'Tamil', 'nativeName': 'தமிழ்'}},
    {'tat': {'name': 'Tatar', 'nativeName': 'татар теле'}},
    {'tel': {'name': 'Telugu', 'nativeName': 'తెలుగు'}},
    {'tgk': {'name': 'Tajik', 'nativeName': 'тоҷикӣ'}},
    {'tgl': {'name': 'Tagalog', 'nativeName': 'Wikang Tagalog'}},
    {'tha': {'name': 'Thai', 'nativeName': 'ไทย'}},
    {'tir': {'name': 'Tigrinya', 'nativeName': 'ትግርኛ'}},
    {'ton': {'name': 'Tonga', 'nativeName': 'faka Tonga'}},
    {'tsn': {'name': 'Tswana', 'nativeName': 'Setswana'}},
    {'tso': {'name': 'Tsonga', 'nativeName': 'Xitsonga'}},
    {'tuk': {'name': 'Turkmen', 'nativeName': 'Türkmen'}},
    {'tur': {'name': 'Turkish', 'nativeName': 'Türkçe'}},
    {'twi': {'name': 'Twi', 'nativeName': 'Twi'}},
    {'uig': {'name': 'Uighur', 'nativeName': 'Uyƣurqə'}},
    {'ukr': {'name': 'Ukrainian', 'nativeName': 'українська мова'}},
    {'urd': {'name': 'Urdu', 'nativeName': 'اردو'}},
    {'uzb': {'name': 'Uzbek', 'nativeName': 'Ozbek'}},
    {'ven': {'name': 'Venda', 'nativeName': 'Tshivenḓa'}},
    {'vie': {'name': 'Vietnamese', 'nativeName': 'Tiếng Việt'}},
    {'vol': {'name': 'Volapük', 'nativeName': 'Volapük'}},
    {'wln': {'name': 'Walloon', 'nativeName': 'walon'}},
    {'wol': {'name': 'Wolof', 'nativeName': 'Wollof'}},
    {'xho': {'name': 'Xhosa', 'nativeName': 'isiXhosa'}},
    {'yid': {'name': 'Yiddish', 'nativeName': 'ייִדיש'}},
    {'yor': {'name': 'Yoruba', 'nativeName': 'Yorùbá'}},
    {'yue': {'name': 'Chinese - Cantonese', 'nativeName': '粵語'}},
    {'zha': {'name': 'Zhuang', 'nativeName': 'Saɯ cueŋƅ'}},
    {'zho': {'name': 'Chinese - China', 'nativeName': '大陆简体'}},
    {'zhtw': {'name': 'Chinese - Taiwan', 'nativeName': '臺灣國語'}},
    {'zul': {'name': 'Zulu', 'nativeName': 'isiZulu'}}
]
