# Generated by Django 5.2.1 on 2025-05-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='movie_posters/')),
                ('runtime', models.PositiveIntegerField()),
                ('status', models.CharField(blank=True, max_length=20)),
                ('keep_updated', models.BooleanField(blank=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('tvdb_id', models.PositiveIntegerField()),
                ('imbd_id', models.CharField(blank=True, max_length=16)),
                ('tmbd_id', models.PositiveIntegerField()),
                ('budget', models.PositiveIntegerField()),
                ('box_office', models.PositiveIntegerField()),
                ('country', models.CharField(blank=True, max_length=60)),
                ('language', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'db_table': 'movie',
            },
        ),
    ]
