# Generated by Django 5.2.1 on 2025-06-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('last_updated', models.CharField(db_comment='Date and time when the movie was last updated from TVDB.')),
                ('image', models.ImageField(null=True, upload_to='movie_posters/')),
                ('runtime', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20)),
                ('keep_updated', models.BooleanField()),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tvdb_id', models.PositiveIntegerField(null=True)),
                ('imdb_id', models.CharField(max_length=16, null=True)),
                ('tmdb_id', models.PositiveIntegerField(null=True)),
                ('budget', models.PositiveBigIntegerField(null=True)),
                ('box_office', models.PositiveBigIntegerField(null=True)),
                ('country', models.CharField(blank=True, max_length=60)),
                ('language', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'db_table': 'movie',
            },
        ),
    ]
