# Generated by Django 5.2.3 on 2025-06-10 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='tvdb_id',
            field=models.PositiveIntegerField(),
        ),
    ]
