# Generated by Django 5.2.1 on 2025-06-10 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='imbd_id',
            new_name='imdb_id',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='tmbd_id',
            new_name='tmdb_id',
        ),
    ]
