# Generated by Django 5.2.6 on 2025-11-19 09:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_backdrops_alter_movie_logos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='backdrops',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='movie',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='movie',
            name='logos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='movie',
            name='posters',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='movie',
            name='recommendations',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='movie',
            name='similar',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='movie',
            name='spoken_languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, default=list, size=None),
        ),
    ]
