# Generated by Django 5.2.1 on 2025-06-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_imbd_id_movie_imdb_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='last_updated',
            field=models.CharField(blank=True, db_comment='Date and time when the movie was last updated from TVDB.'),
        ),
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
