# Generated by Django 5.2.1 on 2025-06-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_last_updated_movie_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='box_office',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='budget',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdb_id',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tmdb_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
    ]
